### PR TITLE
add routing in example

### PR DESCRIPTION
**Pull request by hungtuchen**
sorry for mess up server.js
will refactor to what we need later

### CODE REVIEW

**Comment by hungtuchen** [comment]
not merge here, still need to refactor to work

**Comment by transedward** [comment]
the routes can be referenced, we need to do in isomorphic way

**Comment by transedward** [comment]
the routes can be referenced, we need to do in isomorphic way

**Comment by transedward** [comment]
the routes can be referenced, we need to do in isomorphic way

**Comment by hungtuchen** [comment]
the routes can be referenced, we need to do in isomorphic way

**Pull request merged**
